# Generated by Django 3.2.8 on 2023-07-03 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internteam',
            name='id_intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Стажёр'),
        ),
        migrations.AlterField(
            model_name='internteam',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uralapi.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uralapi.eventuts', verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='end_date',
            field=models.DateField(default='1970-01-01', verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='end_estimation_date',
            field=models.DateField(default='1970-01-01', verbose_name='Дата окончания оценки'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='id_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uralapi.team', verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_date',
            field=models.DateField(default='1970-01-01', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uralapi.project', verbose_name='Название проекта'),
        ),
    ]
