# Generated by Django 3.2.8 on 2023-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uralapi', '0002_auto_20230705_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='description_minus_one',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='description_one',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='description_two',
        ),
        migrations.RemoveField(
            model_name='evaluationcriteria',
            name='description_zero',
        ),
        migrations.AddField(
            model_name='evaluationcriteria',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='end_estimation_date',
            field=models.DateField(verbose_name='Дата окончания оценки'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
